# 5pipeline SoC Vivado batch build script
#
# Constraint file: 5pipeline_p5b.xdc
# RTL top:        soc_top
#
# Usage (run in the 5pipeline directory):
#   vivado -mode batch -source build_5pipeline_p5b.tcl
#
# Optional environment variables:
#   FPGA_PART  Override FPGA part. The default matches the DFZU2EG board.
#   JOBS       Parallel Vivado jobs, default 4.
#   BUILD_DIR  Project output directory, default ./vivado_p5b_build.
#   IP_ROOT    Directory containing ddr4_0/ddr4_0.xci, default ./ip.
#
# For a 4EV board, for example:
#   FPGA_PART=xczu4ev-sfvc784-1-e vivado -mode batch \
#       -source build_5pipeline_p5b.tcl
#
# IMPORTANT:
# ddr4_0 is a board-specific MIG IP. Copy the ddr4_0.xci generated by the
# original board project to:
#   5pipeline/ip/ddr4_0/ddr4_0.xci
# The script creates axi_clock_converter_0 and ila_0 automatically when their
# XCI files are not supplied.

set script_dir [file dirname [file normalize [info script]]]

proc env_or_default {name default_value} {
    if {[info exists ::env($name)] && $::env($name) ne ""} {
        return $::env($name)
    }
    return $default_value
}

proc require_file {file_path description} {
    if {![file exists $file_path]} {
        error "$description not found: $file_path"
    }
}

proc add_rtl_file {file_path} {
    require_file $file_path "RTL file"
    add_files -fileset sources_1 -norecurse $file_path
    set_property file_type SystemVerilog [get_files $file_path]
}

proc find_ip_xci {ip_root module_name} {
    set candidates [list \
        [file join $ip_root $module_name "$module_name.xci"] \
        [file join $ip_root "$module_name.xci"] \
    ]

    foreach candidate $candidates {
        if {[file exists $candidate]} {
            return [file normalize $candidate]
        }
    }
    return ""
}

set project_name "5pipeline_p5b"
set top_name     "soc_top"
set part_name    [env_or_default FPGA_PART "xczu2eg-sfvc784-2-e"]
set jobs         [env_or_default JOBS 4]
set build_dir    [file normalize [env_or_default BUILD_DIR \
                      [file join $script_dir vivado_p5b_build]]]
set ip_root      [file normalize [env_or_default IP_ROOT \
                      [file join $script_dir ip]]]
set report_dir   [file join $build_dir reports]
set generated_ip_dir [file join $build_dir generated_ip]

file mkdir $build_dir
file mkdir $report_dir
file mkdir $generated_ip_dir

puts "INFO: project root = $script_dir"
puts "INFO: build dir   = $build_dir"
puts "INFO: FPGA part   = $part_name"
puts "INFO: jobs        = $jobs"

create_project $project_name $build_dir -part $part_name -force
set_property target_language Verilog [current_project]
set_property simulator_language Mixed [current_project]
set_property source_mgmt_mode All [current_project]

# -----------------------------------------------------------------------------
# RTL source list
#
# Only one copy of taxi_axi_if/taxi_arbiter/taxi_penc/crossbar_addr is added.
# The rd and wr Taxi directories contain duplicate definitions of these common
# modules, and compiling both copies would produce duplicate-module errors.
# -----------------------------------------------------------------------------
set rtl_files [list \
    "dma/3interface/axi.sv" \
    "dma/3interface/axis.sv" \
    "dma/3interface/taxi_dma_desc_if.sv" \
    "Ctrl.sv" \
    "if_id.sv" \
    "id_ex.sv" \
    "ex_mem.sv" \
    "mem_wb.sv" \
    "if/pc_reg.sv" \
    "if/mux_pc.sv" \
    "if/inst_ram.sv" \
    "if/icache.sv" \
    "if/if_stage.sv" \
    "id/reg_file.sv" \
    "id/id_req.sv" \
    "id/id.sv" \
    "id/id_stage.sv" \
    "ex_stage/ex_req.sv" \
    "ex_stage/csr_file.sv" \
    "ex_stage/ex.sv" \
    "ex_stage/ex_stage.sv" \
    "mem_stage/dcache.sv" \
    "mem_stage/mem.sv" \
    "mem_stage/mem_stage.sv" \
    "wb_stage/wb_stage.sv" \
    "loader/cdc_sync.sv" \
    "loader/uart/uart_rx.sv" \
    "loader/uart/uart_tx.sv" \
    "loader/uart/top_uart.sv" \
    "loader/loader.sv" \
    "dbg_uart_tx.sv" \
    "axi/bridge/icache_bridge.sv" \
    "axi/bridge/dcache_bridge.sv" \
    "axi/bridge/loader_bridge.sv" \
    "axi/bridge/uart.sv" \
    "axi/bridge/mmio_bridge.sv" \
    "axi/bridge/bridge_top.sv" \
    "axi/bridge/axi2native_uart.sv" \
    "axi/bridge/axi2native_mmio.sv" \
    "mmio_router.sv" \
    "axi/axi_crossbar/rd/taxi_penc.sv" \
    "axi/axi_crossbar/rd/taxi_arbiter.sv" \
    "axi/axi_crossbar/rd/taxi_axi_crossbar_addr.sv" \
    "axi/axi_crossbar/rd/taxi_axi_register_rd.sv" \
    "axi/axi_crossbar/rd/taxi_axi_crossbar_rd.sv" \
    "axi/axi_crossbar/wr/taxi_axi_register_wr.sv" \
    "axi/axi_crossbar/wr/taxi_axi_crossbar_wr.sv" \
    "axi/axi_crossbar/taxi_axi_crossbar_3s.sv" \
    "coprocessor/bram_for_acc.sv" \
    "dma/dma_ctrl.sv" \
    "dma/taxi_axi_dma_rd.sv" \
    "dma/taxi_axi_dma_wr.sv" \
    "dma/taxi_axi_dma.sv" \
    "dma/dma_subsystem_top.sv" \
    "soc_top.sv" \
]

foreach relative_path $rtl_files {
    add_rtl_file [file normalize [file join $script_dir $relative_path]]
}

# All `include "define.sv" statements resolve from the project RTL root.
set_property include_dirs [list $script_dir] [get_filesets sources_1]

# -----------------------------------------------------------------------------
# Constraints
# -----------------------------------------------------------------------------
set xdc_file [file normalize [file join $script_dir "5pipeline_p5b.xdc"]]
require_file $xdc_file "Constraint file"
add_files -fileset constrs_1 -norecurse $xdc_file
set_property used_in_synthesis true  [get_files $xdc_file]
set_property used_in_implementation true [get_files $xdc_file]

# -----------------------------------------------------------------------------
# Vivado IP
# -----------------------------------------------------------------------------

# DDR4 MIG: must use the board-tested XCI because memory device/timing/pin-bank
# settings cannot be inferred safely from the RTL port list alone.
set ddr4_xci [find_ip_xci $ip_root "ddr4_0"]
if {$ddr4_xci eq ""} {
    error "Missing board-specific DDR4 MIG IP. Copy ddr4_0.xci to: [file join $ip_root ddr4_0 ddr4_0.xci]"
}
add_files -fileset sources_1 -norecurse $ddr4_xci

# AXI clock converter: import an existing XCI when present; otherwise generate
# a 32-bit AXI4 converter with 30-bit addresses and 8-bit IDs.
set clock_converter_xci [find_ip_xci $ip_root "axi_clock_converter_0"]
if {$clock_converter_xci ne ""} {
    add_files -fileset sources_1 -norecurse $clock_converter_xci
} else {
    create_ip -name axi_clock_converter -vendor xilinx.com -library ip \
        -module_name axi_clock_converter_0 -dir $generated_ip_dir
    set_property -dict [list \
        CONFIG.PROTOCOL {AXI4} \
        CONFIG.ADDR_WIDTH {30} \
        CONFIG.DATA_WIDTH {32} \
        CONFIG.ID_WIDTH {8} \
        CONFIG.ACLK_ASYNC {1} \
        CONFIG.SYNCHRONIZATION_STAGES {2} \
    ] [get_ips axi_clock_converter_0]
}

# ILA probe widths match the u_ila instance in soc_top.sv:
# probe0..3/5/6 are 32-bit counters; probe4 is a one-bit completion flag.
set ila_xci [find_ip_xci $ip_root "ila_0"]
if {$ila_xci ne ""} {
    add_files -fileset sources_1 -norecurse $ila_xci
} else {
    create_ip -name ila -vendor xilinx.com -library ip \
        -module_name ila_0 -dir $generated_ip_dir
    set_property -dict [list \
        CONFIG.C_NUM_OF_PROBES {7} \
        CONFIG.C_DATA_DEPTH {1024} \
        CONFIG.C_PROBE0_WIDTH {32} \
        CONFIG.C_PROBE1_WIDTH {32} \
        CONFIG.C_PROBE2_WIDTH {32} \
        CONFIG.C_PROBE3_WIDTH {32} \
        CONFIG.C_PROBE4_WIDTH {1} \
        CONFIG.C_PROBE5_WIDTH {32} \
        CONFIG.C_PROBE6_WIDTH {32} \
    ] [get_ips ila_0]
}

# Generate output products for imported and newly created IP.
generate_target all [get_ips]
export_ip_user_files -of_objects [get_ips] -no_script -sync -force -quiet

# -----------------------------------------------------------------------------
# Compile order and top
# -----------------------------------------------------------------------------
set_property top $top_name [get_filesets sources_1]
update_compile_order -fileset sources_1

puts "INFO: checking RTL hierarchy before synthesis"
synth_design -rtl -name rtl_1 -top $top_name -part $part_name
report_compile_order -used_in synthesis \
    -file [file join $report_dir compile_order.rpt]
close_design

# -----------------------------------------------------------------------------
# Synthesis
# -----------------------------------------------------------------------------
puts "INFO: starting synthesis"
launch_runs synth_1 -jobs $jobs
wait_on_run synth_1

set synth_status [get_property STATUS [get_runs synth_1]]
puts "INFO: synth_1 status = $synth_status"
if {![string match "*Complete*" $synth_status]} {
    error "Synthesis failed. Check: [file join $build_dir 5pipeline_p5b.runs synth_1 runme.log]"
}

open_run synth_1
report_utilization -file [file join $report_dir utilization_synth.rpt]
report_timing_summary -file [file join $report_dir timing_synth.rpt]
report_drc -file [file join $report_dir drc_synth.rpt]
close_design

# -----------------------------------------------------------------------------
# Implementation and bitstream
# -----------------------------------------------------------------------------
puts "INFO: starting implementation and bitstream generation"
launch_runs impl_1 -to_step write_bitstream -jobs $jobs
wait_on_run impl_1

set impl_status [get_property STATUS [get_runs impl_1]]
puts "INFO: impl_1 status = $impl_status"
if {![string match "*Complete*" $impl_status]} {
    error "Implementation failed. Check: [file join $build_dir 5pipeline_p5b.runs impl_1 runme.log]"
}

open_run impl_1
report_utilization -file [file join $report_dir utilization_impl.rpt]
report_timing_summary -delay_type min_max -report_unconstrained \
    -check_timing_verbose -file [file join $report_dir timing_impl.rpt]
report_drc -file [file join $report_dir drc_impl.rpt]
report_power -file [file join $report_dir power_impl.rpt]

set bit_file [file join $build_dir "5pipeline_p5b.runs" "impl_1" "$top_name.bit"]
puts "INFO: build completed"
puts "INFO: bitstream = $bit_file"
puts "INFO: reports   = $report_dir"
